#!/bin/sh

source ./common

set -e

# Create a Kubernetes cluster
gcloud alpha container clusters create \
  --enable-kubernetes-alpha \
  --num-nodes 4 \
  --accelerator type=nvidia-tesla-p100,count=1 \
  --machine-type n1-standard-4 \
  --min-cpu-platform "Intel Broadwell" \
  --disk-size 30 \
  $CLUSTER_NAME

# Fetch its credentials so we can use kubectl locally
gcloud container clusters get-credentials $CLUSTER_NAME

# Import the credentials into the cluster as a secret
kubectl create secret generic ${SERVICE_ACCOUNT}-creds --from-file=service-account.json=${SERVICE_ACCOUNT}-key.json
