#!/bin/sh

source ./common.sh
source ./utils.sh

set -e

echo "Using Project:      ${PROJECT}"
echo "Using Zone:         ${ZONE}"
echo "Using Cluster Name: ${CLUSTER_NAME}"
echo "Using K8S Version:  ${K8S_VERSION}"

# Create a Kubernetes cluster
# Note, we require Intel Broadwells since they are a bit newer, and can provide
# up to a 30% speedup, since we're so CPU bound.
gcloud beta container clusters create \
  --num-nodes 3 \
  --machine-type n1-standard-8 \
  --min-cpu-platform "Intel Broadwell" \
  --disk-size 30 \
  --zone $ZONE \
  --project $PROJECT \
  $CLUSTER_NAME

# Fetch its credentials so we can use kubectl locally
gcloud container clusters get-credentials $CLUSTER_NAME --project $PROJECT --zone $ZONE

create_gcs_bucket
create_service_account_key

# Import the credentials into the cluster as a secret
kubectl create secret generic ${SERVICE_ACCOUNT}-creds --from-file=service-account.json=${SERVICE_ACCOUNT_KEY_LOCATION}
