#!/bin/sh

source ./common

set -e

# Create a Kubernetes cluster
gcloud alpha container clusters create \
  --enable-kubernetes-alpha \
  --num-nodes 5 \
  --accelerator type=nvidia-tesla-k80,count=1 \
  --machine-type n1-standard-2 \
  --disk-size 20 \
  --preemptible \
  --cluster-ipv4-cidr=10.0.0.0/10 \
  --zone=asia-east1-a \
  $CLUSTER_NAME

# Fetch its credentials so we can use kubectl locally
gcloud container clusters get-credentials $CLUSTER_NAME

# Import the credentials into the cluster as a secret
kubectl create secret generic ${SERVICE_ACCOUNT}-creds --from-file=service-account.json=${SERVICE_ACCOUNT}-key.json
