#!/bin/sh

set -ex

source ./common.sh

# Create a GCS bucket for data storage
gsutil mb -p $PROJECT gs://$BUCKET_NAME

# Make a service account for our containers
gcloud iam service-accounts create $SERVICE_ACCOUNT --project=$PROJECT

# Grant it read/write permissions on our bucket
gsutil acl ch -u ${SERVICE_ACCOUNT_EMAIL}:W gs://$BUCKET_NAME

# Get keys for the service account
gcloud iam service-accounts keys create \
  ${SERVICE_ACCOUNT}-key.json \
  --iam-account $SERVICE_ACCOUNT_EMAIL

gcloud projects add-iam-policy-binding $PROJECT \
  --member serviceAccount:$SERVICE_ACCOUNT_EMAIL \
  --role roles/storage.objectAdmin \
  --project $PROJECT
