#!/bin/sh

source ./common.sh

./cluster-down

# Left here for documentation, if you really wish to delete more things:
#
# gcloud iam service-accounts delete $SERVICE_ACCOUNT_EMAIL

# gsutil -m rm -r gs://$BUCKET_NAME
