FROM gcr.io/tensor-go/cc-base:0.17

COPY evaluator_cc_wrapper.sh /app

ADD staging/ /app
RUN bazel build -c opt --define=board_size=19 --define=tf=1 cc/main

CMD ["/bin/sh", "evaluator_cc_wrapper.sh"]
