package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache License 2.0

cc_library(
    name = "file",
    srcs = [
        "path.cc",
        "util.cc",
    ],
    hdrs = [
        "path.h",
        "util.h",
    ],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)
