package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "file",
    srcs = [
        "filesystem.cc",
        "helpers.cc",
        "path.cc",
    ],
    hdrs = [
        "filesystem.h",
        "helpers.h",
        "path.h",
    ],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)
